[package]
name = "lib-meta"
version = "0.0.1"
authors = [ "Kostas Tzoumpas <tzoumpas.ks@gmail.com>"]
edition = "2021"
publish = false

[dependencies.lib]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.0"
